<a href="https://colab.research.google.com/github/AHANIK33/Machine-Learning/blob/main/Bangladesh_Student_Performance_update.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder,OneHotEncoder,LabelEncoder,StandardScaler,MinMaxScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression,SGDRegressor
from sklearn.metrics import mean_squared_error,r2_score,root_mean_squared_error,mean_absolute_error

In [ ]:
df = pd.read_csv("/content/bangladesh_student_performance_updated.csv")
df

,date,gender,age,address,famsize,Pstatus,M_Edu,F_Edu,M_Job,F_Job,relationship,smoker,tuition_fee,time_friends,ssc_result,hsc_result
0,29/04/2018,M,18.0,Rural,GT3,Together,3,2,At_home,Farmer,No,No,71672.0,4,4.22,3.72
1,29/04/2018,F,19.0,Rural,LE3,Apart,0,4,Other,Health,Yes,No,26085.0,5,3.47,2.62
2,29/04/2018,F,19.0,Rural,GT3,Together,0,3,Teacher,Services,No,No,40891.0,3,3.32,2.56
3,29/04/2018,F,19.0,Rural,LE3,Apart,2,3,At_home,Business,No,No,50600.0,2,4.57,4.17
4,29/04/2018,M,17.0,Rural,GT3,Together,1,1,At_home,Farmer,No,No,62458.0,2,4.50,3.94
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,29/04/2018,M,18.0,Urban,GT3,Together,2,2,Teacher,Health,No,No,108426.0,2,3.57,3.18
2014,29/04/2018,M,19.0,Urban,GT3,Together,0,3,Other,Teacher,Yes,No,100665.0,5,4.05,3.13
2015,29/04/2018,M,18.0,Urban,GT3,Together,3,2,Services,Farmer,Yes,No,92291.0,1,3.93,3.15
2016,29/04/2018,M,19.0,Rural,GT3,Together,0,2,At_home,Teacher,No,No,43926.0,3,3.34,2.83
2017,29/04/2018,F,18.0,Rural,LE3,Together,0,2,Teacher,Teacher,No,No,51154.0,3,3.60,3.15

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
nominal_cat = ['gender','address','famsize','Pstatus','M_Job','F_Job','relationship','smoker']
numerical_col = ['age','tuition_fee','ssc_result']

In [ ]:
nominal_transformer = Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='most_frequent')),
        ('encoder',OneHotEncoder(sparse_output=False,handle_unknown='ignore'))
    ]
)
nominal_transformer

Pipeline(steps=[('imputer', SimpleImputer(strategy='most_frequent')),
                ('encoder',
                 OneHotEncoder(handle_unknown='ignore', sparse_output=False))])

In [ ]:
numerical_transformer=Pipeline(
    steps=[
        ('imputer',SimpleImputer(strategy='mean')),
        ('scaler',StandardScaler())
    ]
)
numerical_transformer

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler())])

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        ('nominal',nominal_transformer,nominal_cat),
        ('numerical',numerical_transformer,numerical_col)
    ],
    remainder='passthrough'
)
preprocessor

ColumnTransformer(remainder='passthrough',
                  transformers=[('nominal',
                                 Pipeline(steps=[('imputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('encoder',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False))]),
                                 ['gender', 'address', 'famsize', 'Pstatus',
                                  'M_Job', 'F_Job', 'relationship', 'smoker']),
                                ('numerical',
                                 Pipeline(steps=[('imputer', SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'tuition_fee', 'ssc_result'])])

In [ ]:
X = df.drop(['date','hsc_result'],axis=1)
y = df['hsc_result']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train

,gender,age,address,famsize,Pstatus,M_Edu,F_Edu,M_Job,F_Job,relationship,smoker,tuition_fee,time_friends,ssc_result
746,M,19.0,Rural,LE3,Together,2,2,Other,Services,No,No,49318.0,3,4.95
1381,M,17.0,Urban,GT3,Together,0,1,Health,Farmer,No,Yes,88032.0,5,2.68
240,F,17.0,Urban,GT3,Together,4,3,Other,Services,No,No,116230.0,4,3.75
1646,M,18.0,Urban,LE3,Apart,2,1,Other,Business,No,No,79334.0,3,3.70
1460,M,18.0,Rural,GT3,Apart,4,3,At_home,Farmer,No,No,80248.0,2,3.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,F,18.0,Rural,GT3,Together,2,2,At_home,Health,No,No,50003.0,1,3.83
1294,F,19.0,Urban,LE3,Together,2,3,At_home,Farmer,Yes,No,110895.0,2,3.30
860,F,19.0,Rural,GT3,Together,0,2,Health,Farmer,No,No,51576.0,1,5.00
1459,F,18.0,Rural,GT3,Together,2,4,Other,Services,No,No,45830.0,1,4.42
1126,M,17.0,Rural,GT3,Together,3,4,NaN,Services,Yes,No,79179.0,1,3.38

In [ ]:
lr_pipe = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('regressor',LinearRegression())
    ]
)
lr_pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nominal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'address',
                                                   'famsize', 'Pstatus',
                                                   'M_Job', 'F_Job',
                                                   'relationship', 'smoker']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'tuition_fee',
                                                   'ssc_result'])])),
                ('regressor', LinearRegression())])

In [ ]:
lr_pipe.predict(X_test)
#y_pred = pd.Series(
#    lr_pipe.predict(X_test),
#    index=X_test.index,
#    name="Prediction"
#)

#print(y_pred.head(10))

array([3.22566531, 3.75147018, 3.83019613, 4.00664186, 3.90886468,
       3.33301608, 3.9843285 , 2.54037997, 1.97886626, 3.27239028,
       3.67549746, 2.91990239, 3.23829796, 4.27797546, 3.03907632,
       2.67683989, 3.71729372, 3.45240833, 2.8064922 , 2.96057683,
       2.82062305, 3.20485147, 2.99957398, 3.21864928, 1.89881831,
       2.58370593, 3.18675035, 3.82959511, 3.08845188, 3.94801852,
       2.39854271, 3.94466671, 4.31696495, 2.56460476, 3.19397834,
       3.26413536, 2.75935124, 3.65848872, 2.48692797, 2.60907848,
       3.07614707, 2.97405288, 3.73760615, 2.76965129, 2.17795697,
       3.0682365 , 2.62107646, 2.60926091, 4.03558054, 3.26099047,
       3.07457897, 3.45268988, 4.23316558, 3.63562822, 3.07047904,
       3.19897028, 3.29199946, 2.67475419, 3.81647227, 2.67135675,
       3.00589862, 2.76737407, 2.49028194, 4.43360442, 2.5597574 ,
       3.21127693, 3.96661533, 2.67087186, 3.03353973, 3.22560591,
       3.03057043, 2.72163419, 2.61374344, 3.63605177, 3.07885168,
       2.82564256, 3.66787547, 2.97747772, 2.44436905, 4.04379356,
       3.5222424 , 2.72708514, 3.21005589, 3.14108785, 2.33149071,
       3.43701844, 3.82090899, 2.60604202, 2.82978343, 4.08692177,
       3.84507346, 3.02354688, 2.84583447, 2.86545503, 3.27943732,
       2.76840259, 2.993627  , 2.45809236, 2.71412241, 3.25922199,
       3.26412603, 3.13805115, 2.8707994 , 2.24861276, 2.29239232,
       3.43805722, 3.85677712, 4.18826665, 3.33141201, 1.93292701,
       3.1181356 , 4.0354445 , 3.54075479, 3.08345311, 2.56932757,
       2.1090993 , 4.5162777 , 2.8835292 , 2.64732542, 3.87371073,
       3.6400765 , 3.48216019, 3.08591468, 2.63048989, 4.18403498,
       3.5835169 , 2.38973188, 2.83352021, 3.93166844, 3.63276843,
       1.90130515, 2.80715969, 2.77563252, 2.47218048, 2.78917719,
       2.82096971, 2.64777085, 3.88630488, 3.99397797, 2.92111463,
       4.20760296, 2.9593613 , 3.99531619, 2.83570554, 2.78087061,
       4.38894372, 2.58229103, 3.31774265, 3.31841925, 2.16473011,
       1.98400265, 3.65190783, 3.32881299, 3.47496644, 3.06326072,
       3.46236363, 4.27441681, 4.24736074, 3.07274669, 4.19275168,
       3.67376818, 3.20565371, 3.88579991, 2.05386677, 2.85232705,
       3.16382235, 3.32780009, 3.17250703, 2.44264093, 2.41403489,
       2.58500007, 3.16965222, 2.59373308, 3.04280824, 3.38937418,
       2.65656864, 3.33776052, 1.99102922, 3.87776771, 3.20919278,
       3.91852126, 2.37304837, 3.64502619, 3.89549469, 2.29983665,
       3.58762165, 3.12001856, 4.27274069, 3.09528566, 2.86041244,
       2.39055133, 3.73141761, 3.6817355 , 3.12498231, 2.70992269,
       3.09291035, 2.18675836, 3.05673378, 3.35271999, 2.16598711,
       3.29262482, 3.1780088 , 2.34447347, 4.3914736 , 2.89431491,
       2.68123037, 3.51164801, 3.45274624, 4.17638898, 3.05205745,
       2.76687958, 2.14513762, 2.45958299, 3.69704173, 3.46417838,
       2.97418362, 3.94335385, 2.28342726, 2.51665871, 4.27714999,
       3.44080545, 1.88688877, 3.93486712, 2.51037168, 2.30690014,
       3.44120429, 3.11848835, 3.37119657, 2.77932446, 3.94576353,
       3.34651098, 2.69727497, 3.14528499, 2.30104174, 2.71547991,
       3.29525419, 2.91762473, 3.93826576, 2.50749735, 3.62989217,
       3.63119927, 2.14789075, 3.49945592, 3.50163555, 4.13264843,
       4.10281464, 3.30363764, 3.07363632, 2.33443154, 2.46607124,
       3.47925739, 3.12727438, 3.35043899, 4.06908898, 4.22601433,
       3.50974572, 2.97790495, 3.38319709, 2.93250911, 3.83631873,
       2.99094864, 2.40640255, 3.43305181, 3.15395375, 1.55490415,
       3.25667412, 3.52000919, 2.82818496, 3.55155298, 3.31933596,
       3.24359836, 3.32416284, 3.00395708, 3.08039939, 2.57555043,
       3.31511773, 2.40620331, 4.07354021, 3.66411231, 2.8749422 ,
       1.59151901, 4.48562843, 2.84879714, 2.84859067, 2.80378643,
       3.62108186, 2.93652429, 2.09533344, 2.60401787, 3.65659805,
       3.8402347 , 3.58748354, 2.81321388, 3.59856873, 3.8856199 ,
       2.79043832, 3.29890934, 3.8023542 , 3.90234309, 4.3916884 ,
       3.79179472, 2.3145174 , 2.79799968, 3.71911257, 3.28640963,
       2.81505793, 3.90867994, 3.6144725 , 3.81929294, 3.18307001,
       3.52921727, 2.89004599, 3.70350208, 3.10521004, 2.57022409,
       3.21566587, 2.1393477 , 2.82162681, 3.26718388, 3.13179562,
       3.09991733, 3.80338758, 3.32590532, 3.138291  , 3.93282525,
       3.13996908, 3.30942446, 3.4754222 , 3.12527848, 2.85236409,
       4.50836209, 3.24298408, 2.81773923, 2.85714792, 3.75053515,
       4.22305956, 2.50989565, 3.16186926, 3.60954889, 3.26531766,
       3.89890452, 2.77196692, 3.50822643, 3.53270772, 3.77824734,
       2.59506616, 2.68323324, 2.94058272, 3.04932833, 3.82441965,
       2.4109803 , 2.46487941, 2.10054888, 3.31864499, 3.61212448,
       4.35570151, 3.02481084, 3.44329277, 2.855912  , 3.52573654,
       3.72511861, 3.45271617, 2.44413725, 2.70872369, 3.63392108,
       3.17585471, 3.34049068, 3.82592861, 2.79619428, 3.94613035,
       2.88710634, 3.16137974, 2.67625309, 3.20836784, 3.21607364,
       3.86046694, 3.43772438, 3.08661666, 2.02235148, 3.64178718,
       4.1190538 , 3.81852055, 3.63033136, 3.17029988, 3.88481616,
       3.17771376, 3.74947812, 3.08727045, 3.97334401, 3.20119923,
       3.72362208, 3.34136254, 2.8011317 , 3.09953423, 2.68191901,
       3.59132411, 3.27387962, 2.53352473, 3.45188659, 2.96011046,
       2.37453904, 3.38673632, 3.55296042, 2.34384864])

In [ ]:
sgd_pipe = Pipeline(
    steps=[
        ('preprocessor',preprocessor),
        ('regressor',SGDRegressor())
    ]
)
sgd_pipe.fit(X_train,y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('nominal',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['gender', 'address',
                                                   'famsize', 'Pstatus',
                                                   'M_Job', 'F_Job',
                                                   'relationship', 'smoker']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'tuition_fee',
                                                   'ssc_result'])])),
                ('regressor', SGDRegressor())])

In [ ]:
sgd_pipe.predict(X_test)

array([3.22177171, 3.78937391, 3.84743054, 3.94707509, 3.84149077,
       3.36642004, 3.94459869, 2.52628303, 1.97809014, 3.29944899,
       3.68794645, 2.94040394, 3.25544032, 4.29576957, 3.07077603,
       2.64637923, 3.72116441, 3.39668725, 2.82735552, 2.95020088,
       2.84349467, 3.23274361, 2.96318078, 3.20948818, 1.92385502,
       2.49995906, 3.22997289, 3.83359055, 3.05023243, 3.97046111,
       2.42346529, 3.96929554, 4.27578248, 2.60253863, 3.21785086,
       3.30084529, 2.78603567, 3.69275875, 2.52002554, 2.63308212,
       3.10714751, 2.997303  , 3.74624104, 2.79493071, 2.14283276,
       3.10569889, 2.67064432, 2.61170033, 3.98486462, 3.24331694,
       3.07502758, 3.47042894, 4.21581649, 3.62864718, 3.06665448,
       3.16366203, 3.32545337, 2.68455994, 3.8356121 , 2.60963583,
       3.04545785, 2.78575102, 2.49776181, 4.44606437, 2.59153007,
       3.23095844, 3.91786153, 2.69276135, 3.05190984, 3.20095369,
       3.04744401, 2.76506663, 2.63934452, 3.67201857, 3.09262494,
       2.85510596, 3.68382585, 2.99761841, 2.39159193, 4.06832088,
       3.55633429, 2.68296801, 3.22487002, 3.13053162, 2.33947887,
       3.44815697, 3.84232653, 2.61206286, 2.844353  , 4.08071046,
       3.84287191, 3.05229469, 2.86844487, 2.89163531, 3.22375734,
       2.78956145, 2.88550069, 2.47497103, 2.72297338, 3.26138823,
       3.26723778, 3.17238417, 2.87990799, 2.27771797, 2.29474734,
       3.38767611, 3.84295228, 4.22133979, 3.30525357, 1.95365432,
       3.14789452, 4.05684489, 3.56571886, 3.0898296 , 2.60750901,
       2.12784029, 4.53988404, 2.90607066, 2.59179865, 3.87763066,
       3.66289792, 3.48561441, 3.09431872, 2.62789425, 4.18836168,
       3.60895089, 2.40055276, 2.81794459, 3.95805779, 3.62169265,
       1.93690429, 2.82107626, 2.76870107, 2.48494555, 2.81545632,
       2.82313482, 2.68179179, 3.92038711, 3.97019603, 2.93037942,
       4.24617311, 2.9752412 , 4.03556   , 2.87044342, 2.78807658,
       4.38470433, 2.58230205, 3.34311847, 3.36345816, 2.14044628,
       2.02551294, 3.69090759, 3.3606752 , 3.50383072, 3.0742443 ,
       3.4749451 , 4.28813232, 4.24697649, 3.08720076, 4.2129899 ,
       3.674839  , 3.21339071, 3.92293431, 2.00456933, 2.87610183,
       3.15529026, 3.3208585 , 3.188418  , 2.4621152 , 2.36312079,
       2.57020911, 3.17503813, 2.63012589, 3.02587872, 3.41053154,
       2.61772098, 3.34585093, 2.03253414, 3.87312957, 3.21421258,
       3.9205296 , 2.39311862, 3.65817171, 3.90926675, 2.3316489 ,
       3.58641457, 3.1375382 , 4.20528709, 3.12984984, 2.89685265,
       2.41232347, 3.73422034, 3.66645432, 3.13527882, 2.60992748,
       3.12082468, 2.20771542, 3.07389803, 3.37080503, 2.20059818,
       3.32255258, 3.22636352, 2.36883788, 4.42299238, 2.90743308,
       2.6287081 , 3.52500375, 3.45412789, 4.19922018, 3.00339258,
       2.79789081, 2.12844088, 2.49950296, 3.69383499, 3.44676352,
       2.95416863, 3.96951282, 2.32649196, 2.52825351, 4.26708913,
       3.35440373, 1.91702698, 3.96014525, 2.50520583, 2.34004828,
       3.46351316, 3.1447373 , 3.37808757, 2.80090391, 3.98231461,
       3.29726262, 2.72032931, 3.1692592 , 2.32782543, 2.73300469,
       3.30492418, 2.91912966, 3.94820042, 2.53380751, 3.63304958,
       3.64189406, 2.11801498, 3.52844111, 3.45930177, 4.15672766,
       4.13133606, 3.33143081, 3.0935111 , 2.32975255, 2.50576767,
       3.4958256 , 3.14039982, 3.31220239, 4.04384267, 4.22164945,
       3.53486426, 2.97802935, 3.40310432, 2.94604576, 3.85551352,
       3.0034612 , 2.43487116, 3.43521856, 3.15764162, 1.59180674,
       3.25857893, 3.53518028, 2.85497128, 3.56073122, 3.36729403,
       3.28651445, 3.33785737, 3.03652097, 3.10128038, 2.61617666,
       3.2803839 , 2.42688149, 4.1014651 , 3.68396154, 2.82721646,
       1.5993039 , 4.49010622, 2.8610128 , 2.87171972, 2.7893563 ,
       3.64150685, 2.93361849, 2.12714932, 2.60507591, 3.57952613,
       3.84193643, 3.60958389, 2.82289078, 3.62658746, 3.90348549,
       2.81988356, 3.3096409 , 3.7905413 , 3.93554165, 4.41771631,
       3.81563124, 2.32652299, 2.84682233, 3.73581502, 3.30491569,
       2.8235571 , 3.928322  , 3.64161597, 3.81991613, 3.20587559,
       3.55124194, 2.90499563, 3.71433252, 3.11418094, 2.52743188,
       3.23422286, 2.16871844, 2.86484145, 3.28283186, 3.13743918,
       3.05370159, 3.82439324, 3.34205566, 3.12927645, 3.93397765,
       3.1014196 , 3.32775611, 3.48501085, 3.13698454, 2.86282249,
       4.52457655, 3.25321492, 2.79548583, 2.87504651, 3.77596364,
       4.23626895, 2.48046815, 3.17180464, 3.62722271, 3.28519334,
       3.92263859, 2.79412463, 3.51265838, 3.56005321, 3.74641506,
       2.62764939, 2.63275553, 2.97438672, 3.07060656, 3.85165184,
       2.41722655, 2.49698822, 2.13067476, 3.27920801, 3.57003218,
       4.380077  , 3.04297991, 3.38198379, 2.87001006, 3.5442861 ,
       3.77994482, 3.49082901, 2.46432583, 2.68892577, 3.63966438,
       3.18178055, 3.34718407, 3.84685994, 2.81695118, 3.9351247 ,
       2.9030758 , 3.17932075, 2.62498923, 3.21067607, 3.23963391,
       3.87422013, 3.45747803, 3.08113394, 2.03213568, 3.65743895,
       4.14817396, 3.83213744, 3.62587392, 3.12620016, 3.88613164,
       3.17807292, 3.73047882, 3.09682075, 3.92127357, 3.22437701,
       3.76987212, 3.38845349, 2.79678766, 3.10020729, 2.70262442,
       3.53576489, 3.29584228, 2.5489689 , 3.46712676, 2.94020792,
       2.39796879, 3.39317205, 3.55953233, 2.35542851])

In [ ]:
y_pred = lr_pipe.predict(X_test)
print(f"MSE:{round(mean_squared_error(y_test,y_pred),4)}")
print(f"RMSE:{round(root_mean_squared_error(y_test,y_pred),4)}")
print(f"MAE:{round(mean_absolute_error(y_test,y_pred),4)}")
print(f"R2 Score:{round(r2_score(y_test,y_pred),4)}")

MSE:0.0203
RMSE:0.1425
MAE:0.1114
R2 Score:0.9459

In [ ]:
y_pred = sgd_pipe.predict(X_test)
print(f"MSE:{round(mean_squared_error(y_test,y_pred),4)}")
print(f"RMSE:{round(root_mean_squared_error(y_test,y_pred),4)}")
print(f"MAE:{round(mean_absolute_error(y_test,y_pred),4)}")
print(f"R2 Score:{round(r2_score(y_test,y_pred),4)}")

MSE:0.0204
RMSE:0.143
MAE:0.1126
R2 Score:0.9455

In [ ]:
y_pred = lr_pipe.predict(X_test)

result = pd.DataFrame({
    'Actual HSC Result': y_test.values,
    'Predicted HSC Result': y_pred
})

result.head(100)

    Actual HSC Result  Predicted HSC Result
0                3.19              3.225665
1                3.70              3.751470
2                3.82              3.830196
3                3.80              4.006642
4                3.98              3.908865
..                ...                   ...
95               2.80              2.768403
96               2.96              2.993627
97               2.42              2.458092
98               2.75              2.714122
99               3.16              3.259222

[100 rows x 2 columns]

In [ ]:
new_student = pd.DataFrame({
    'gender': ['Male'],
    'address': ['Urban'],
    'famsize': ['GT3'],
    'Pstatus': ['Together'],
    'M_Job': ['Teacher'],
    'F_Job': ['Business'],
    'relationship': ['Good'],
    'smoker': ['No'],
    'age': [18],
    'tuition_fee': [5000],
    'ssc_result': [4.80],
    'F_Edu': [12],
    'M_Edu': [14],
    'time_friends': [3]
})

prediction = lr_pipe.predict(new_student)
print(prediction)

[4.9373215]