<a href="https://colab.research.google.com/github/AHANIK33/Machine-Learning/blob/main/IMDB_text_based_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report
from sklearn.pipeline import Pipeline
import csv

In [7]:
df = pd.read_csv('/content/imdb_labelled.csv',sep = '\t', header=None,names=['review','sentiment'],engine='python',on_bad_lines='skip')
df.dropna(subset=['sentiment'],inplace=True)
df['sentiment']=df['sentiment'].astype(int)
df

                                                review  sentiment
26   To sum the film up,"Breeders"" is a terrible, ...          0
27                                  Not recommended.            0
28   He is almost unbearable to watch on screen, he...          0
29   Aside from it's terrible lead, this film has l...          0
30   I understand that it's supposed to be a cheap ...          0
..                                                 ...        ...
449  I just got bored watching Jessice Lange take h...          0
450  Unfortunately, any virtue in this film's produ...          0
451                   In a word, it is embarrassing.            0
452                               Exceptionally bad!            0
453  All in all its an insult to one's intelligence...          0

[428 rows x 2 columns]

In [9]:
df.head(30)

                                               review  sentiment
26  To sum the film up,"Breeders"" is a terrible, ...          0
27                                 Not recommended.            0
28  He is almost unbearable to watch on screen, he...          0
29  Aside from it's terrible lead, this film has l...          0
30  I understand that it's supposed to be a cheap ...          0
31  Lewis Black's considerable talent is wasted he...          0
32  The film's sole bright spot was Jonah Hill (wh...          1
33  With the originality and freshness of the firs...          0
34           The budget was evidently very limited.            0
35  This was reflected not only in the cast, but a...          0
36  However, here there was no decent acting, acti...          0
37                     Filmiing was less expansive.            0
38  It failed to convey the broad sweep of landsca...          0
39           Generally; it just lacked imagination.            0
40                                 Not recommended.            0
41  Is it possible for a movie to get any worse th...          0
42  There is no plot here to keep you going in the...          0
43  Even when the women finally show up, there is ...          0
44  Beware: this is not a trashy cult movie, this ...          0
45   I can't believe there's even a sequel to this!            0
46  Which is precisely why I am giving it such a b...          0
47  Being a 90's child, I truly enjoyed this show ...          1
48  But ""Tiny Toons"" kept the 90's vibe and deli...          1
49  The memories are murky but I can only say that...          1
50  Easily, none other cartoon made me laugh in a ...          1
51  The characters were all funny and had the pecu...          1
52  Every single character was hilarious and deser...          1
53  Every element of this story was so over the to...          0
54  Her lines seem to have been WRITTEN by a fifte...          0
55  Perabo has a nice energy level and is obviousl...          1

In [10]:
X = df['review']
y = df['sentiment']

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [31]:
model = Pipeline([
    ('vectorizer',TfidfVectorizer(stop_words="english")),
    ('classifier',MultinomialNB())
])

In [32]:
model.fit(X_train,y_train)

Pipeline(steps=[('vectorizer', TfidfVectorizer(stop_words='english')),
                ('classifier', MultinomialNB())])

In [33]:
y_pred = model.predict(X_test)

In [34]:
y_pred

array([1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0])

In [35]:
accuracy = accuracy_score(y_test,y_pred)
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 76.74%

In [36]:
report = classification_report(y_test,y_pred)
print("Classification Report:\n",report)

Classification Report:
               precision    recall  f1-score   support

           0       0.79      0.56      0.66        34
           1       0.76      0.90      0.82        52

    accuracy                           0.77        86
   macro avg       0.77      0.73      0.74        86
weighted avg       0.77      0.77      0.76        86

In [39]:
review = ["he is Good"]
prediction = model.predict(review)
print("Prediction:",prediction[0])

Prediction: 1